env:
  browser: true
  commonjs: true
  es6: true
  node: true
  screeps/screeps: true
extends: 'screeps'
plugins:
  - screeps
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
