env:
  screeps/screeps: true
  browser: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'screeps'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
plugins:
  - 'screeps'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
